### ISSUE TITLE
Refactor the view layer

### ISSUE THREAD

**Issue by OrangeNote** [OrangeNote/RuneBook#14]
I found Riot and Freezer easy to learn. But I have the impression that I'm not using them properly.

So currently the code for the view layer and the way I manage the store are a bit messy and they might need some refactoring or even an entire rewrite, if I consider migrating the view layer to a better framework like Vue or React, as suggested by @BonusPlay.

Still unsure, probably short term refactor, long term rewrite.

**Comment by BonusPlay** [comment]
I have started the transition on [my fork](https://github.com/BonusPlay/RuneBook). I'm 100% sure I'm gonna need some help with css, but other than that the transition to vue2 + vex is going pretty well. I'll be sure to upload current progress from my local branch to my fork today evening.
