### ISSUE TITLE
Add item sets

### ISSUE THREAD

**Issue by MingweiSamuel** [OrangeNote/RuneBook#21]
Item sets are clearly out of the scope of the original project. But given the convenience of popping a rune page into the LCU, and the nice third party plugin integration, it would be really convenient to be able to pop an item set build before the game starts as well. This would make the app more into a  great one-click place to plan out a game before loading in.

I'm willing to contribute to this or other issues.

**Comment by OrangeNote** [comment]
Championify is already such a great tool and I think it's enough for what it does. Personally as a player, I don't think I'll ever need the feature you're mentioning. Item sets are a different beast, there's no reason to think, in champion select, about items you'll buy in game when you can just search and buy them at any time. And it's like reinventing the wheel: Riot already offers a complete item set editor (of course you need to design ahead your sets). And then there's [feature creep](https://en.wikipedia.org/wiki/Feature_creep). So yeah completely out of scope for me. Maybe you could ask the author of Championify for such a feature if you really believe in it. I'm leaving this issue open for further discussion 😃

**Comment by MingweiSamuel** [comment]
Fair enough, I don't have much more to add. Feel free to close

**Comment by OrangeNote** [comment]
Thanks for sharing your thoughts anyway.
