### ISSUE TITLE
Thoughts? League theme.

### ISSUE THREAD

**Issue by Arxarius** [OrangeNote/RuneBook#26]
[https://imgur.com/mYowylR](https://imgur.com/mYowylR)

Would be cool to have a league theme for the app.

**Comment by OrangeNote** [comment]
That's actually what I originally planned. But then it become a low priority feature and I ended up releasing it with the default semantic-ui theme. Now I don't know what to do because there's a PR #22 for Dark Mode. I liked the idea of having a switch for light/dark mode. Maybe we could merge the two things and make a Dark mode AND a Light mode with custom lol theme. How does it sound?

**Comment by OrangeNote** [comment]
Oh and btw your preview is awesome!

**Comment by Arxarius** [comment]
That sounds awesome, mine was just with the inspector i would need to code it up on my fork and do a pull request. Could even implement a settings function to change the theme along with other aspects.

**Comment by clabby** [comment]
I'd be glad to alter #22 with a LoL themed dark mode rather than a simple inverted color scheme. If you're (@Arxarius) already on this let me know!

**Comment by OrangeNote** [comment]
For themes we could use the same color schemes from Nexus site ([reference](https://nexus.leagueoflegends.com/en-us/2018/02/ask-riot-balancing-champions/), switch the theme to notice that a lot of colors don't change when you switch from one to another).

**Comment by OrangeNote** [comment]
Until now I used the CSS-only version of Semantic UI, but if we wish to make themes, we should consider the standard Semantic UI package with LESS support and Gulp for building, I think.

**Comment by clabby** [comment]
Less is the way to go, I’ll get working on a non-binary theme framework tonight.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Arxarius** [comment]
you can keep the standard semantic as it is, building a proper scss structure for our own components is best, less is outdated.

**Comment by clabby** [comment]
@Arxarius I prefer less, but definitely open to scss, so we’ll do that. Should we add support for 3rd party themes?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Arxarius** [comment]
The structure for sass is the same just slight syntax changes and more control. Semantic covers most 3rd party libraries and i can build anythign you ask tbh so we can keep it to our own stuff, i will start a structure now and we can go from there.

**Comment by OrangeNote** [comment]
lol I'm not an expert in CSS and preprocessors so you should decide what's better for everyone.

I don't think we need support for custom theming, I think that's out of scope.

**Comment by Arxarius** [comment]
Agreed

**Comment by Arxarius** [comment]
@OrangeNote pull request #28 has been created.

**Comment by Arxarius** [comment]
I have also made more progress on the dark theme @ my fork

**Comment by clabby** [comment]
Added Grunt/SASS in my fork.
