### ISSUE TITLE
After updating, RuneBook always says to connect to client.

### ISSUE THREAD

**Issue by afisher1117** [OrangeNote/RuneBook#37]
Title. 

Have tried re-opening both client and RuneBook in different orders.

**Comment by OrangeNote** [comment]
Hi, I know the cause of this issue. I made a slightly different version that you can download here https://github.com/OrangeNote/RuneBook/releases/download/v1.5.0-hotfix/RuneBook.Setup.1.5.0.exe

It should temporarily fix this issue. I'm working on a more complete solution including the option to manually specify the installation path if the client is not automatically recognized by RuneBook. Thanks for your patience.

**Comment by OrangeNote** [comment]
v1.5.1 should fix this issue. If not, in the Settings panel you can now manually tell RuneBook where to find your League Client by specifying the installation path

**Comment by afisher1117** [comment]
issue is resolved! thanks for getting back to me so soon!
