### ISSUE TITLE
Application Window Unresponsive to Windows Shortcuts

### ISSUE THREAD

**Issue by RyanCortino** [OrangeNote/RuneBook#44]
The client doesn't seem to react when attempting to move/resize it using [WIN] + [Direction Key]

This has caused a fatal error for me after downsizing from 2 monitors to 1. The Runebook application is still opening on a nonexistent second monitor, and cannot be moved through standard means.

**Comment by OrangeNote** [comment]
There's a file called `window-state.json` inside `C:\Users\USERNAME\AppData\Roaming\RuneBook`. Delete that file and reopen RuneBook to reset the window.

I don't know the reason why the app doesn't react to those commands. Actually I'm not a Windows user and I wasn't aware you could move elements with keyboard. Is it necessary for you to move it the way you described? I mean, is it worth investigating the issue?

**Comment by aberrantGeek** [comment]
As long as the workaround exists, I doubt it needs to be prioritized. They are system-level commands, so it probably SHOULD be looked into at some point.
