### ISSUE TITLE
Please add support for u.gg

### ISSUE THREAD

**Issue by say3r** [OrangeNote/RuneBook#56]
U.gg is a pretty new site for getting champion statistics, but they have good data, and apparently collect from a very large set of games. Would be great if they were a source for this app!

**Comment by OrangeNote** [comment]
Hey! At the moment I'm not planning to add new sources. But RuneBook will always be open to contributions, so if someone else wants to integrate u.gg I'll be happy to support it.

Also note: I visited the site and it's well done, but I think content is generated from JavaScript and that means it's impossible (with current RuneBook tech) to get pages in the same way we did with other sources.

**Comment by OrangeNote** [comment]
#67
