### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by marcelotoledo** [OrangeNote/RuneBook#64]
Apparently new version of runes has come out and app stopped working.

**Comment by PixelHir** [comment]
It won't download new runes from runeforge, even though they added them to the site.
![image](https://user-images.githubusercontent.com/7670940/48783151-fcec3200-ecdf-11e8-933c-02357a587555.png)

**Comment by marcelotoledo** [comment]
It still not working for me. The button that apply the runes appear disabled to me, see in the image below:

Is there anything I can do to help you debug it?

![screen shot 2018-11-20 at 15 45 06](https://user-images.githubusercontent.com/245042/48792388-48501180-ecdb-11e8-9602-1f9a4fd77c56.png)

**Comment by OrangeNote** [comment]
@marcelotoledo you have to select an editable page first in the client. "Dominação: O Carrasco" is one of the preset pages, you can't override it.

**Comment by marcelotoledo** [comment]
It's working, sorry about that.
