### ISSUE TITLE
Check patch version for builds

### ISSUE THREAD

**Issue by BonusPlay** [OrangeNote/RuneBook#7]
Check patch version before using build, otherwise you might end up with build that isn't possible to make (for example this skarrner build is for patch 7.23 and cannot be used on current patch).
![image](https://user-images.githubusercontent.com/8405359/36340412-a44800e8-13dc-11e8-8c0d-2afe3d6e3fa3.png)
![image](https://user-images.githubusercontent.com/8405359/36340419-bef292be-13dc-11e8-9c98-3839380e673c.png)

**Comment by OrangeNote** [comment]
It seems that patch versions on runeforge aren't updated if the page doesn't get changed.

So there are pages that are still valid even if the assigned patch version isn't matching live patch version. Checking against current version would disable all the pages when a new patch goes live.
