### ISSUE TITLE
u.gg tab does not show runes for all champions

### ISSUE THREAD

**Issue by karlojey** [OrangeNote/RuneBook#70]
Hi there,

For some reason, the U.GG tab does not show runes for all champions. For example, I've attached a screenshots showing that Rune Book cannot display runes for Mordekaiser, but it will display runes for Miss Fortune.

![runebook_morde](https://user-images.githubusercontent.com/43248739/50082872-fdb7ab80-022c-11e9-9ac1-8dca9875bf6a.jpg)

![runebook_mf](https://user-images.githubusercontent.com/43248739/50082870-fdb7ab80-022c-11e9-8c17-e509ce71150a.jpg)

**Comment by paolostyle** [comment]
#71 should fix this
