### ISSUE TITLE
Runebook does not display any result from u.gg

### ISSUE THREAD

**Issue by karlojey** [OrangeNote/RuneBook#73]
Dear Team,

Since the update to patch 9.1 on League of Legends, Runebook is unable to display any runes for any champion. Please see the attached screen shot:
![runebook_mf](https://user-images.githubusercontent.com/43248739/51766561-d4d0e300-2115-11e9-933d-a5178e9fb46f.jpg)

**Comment by OrangeNote** [comment]
Thank you, I have already found the issue and I'll publish an update soon.
