### ISSUE TITLE
Unable to upload runes

### ISSUE THREAD

**Issue by juliehyphenanne** [OrangeNote/RuneBook#74]

**Comment by juliehyphenanne** [comment]
Runebook is allowing to connect to client, but all upload buttons are unresponsive

![image](https://user-images.githubusercontent.com/47289874/52173177-f3e50a00-27d2-11e9-8263-4647e8cc034e.png)

**Comment by OrangeNote** [comment]
Make sure you have selected a custom rune page, and not a preset page.

When a preset page is selected, a lock icon is shown near the page name. That means you're not allowed to modify those pages.
