### ISSUE TITLE
Portability. Offline Location of Local Pages

### ISSUE THREAD

**Issue by redsigma** [OrangeNote/RuneBook#77]
Hi, where are the local pages stored on disk. I want to copy the current builds on another pc and im wondering if copying the whole RuneBook folder would do the job. At first i thought the pages were stored in the config.json file but i couldn't find it.

An offline export of all the local pages would be a good feature to have

**Comment by TinyRaindrop** [comment]
`%appdata%/runebook/config.json`

**Comment by redsigma** [comment]
Thanks. I was pretty sure i checked everything in that folder.
