### ISSUE TITLE
"glitches out" too often.... 

### ISSUE THREAD

**Issue by jeske** [OrangeNote/RuneBook#81]
WHen it works, it's great..

However, I'm often getting an error when I try to upload... where it just glitches out.. and then stops communicating with the client. I have to restart Rune Book, and then it'll work for a bit until it glitches out again.

**Comment by TinyRaindrop** [comment]
Never had this issue. Obviously, reinstall everything, also try disabling any antivirus software.

**Comment by jeske** [comment]
I don't run any 3rd party antivirus.... I think "often" might be a bit much... It happened about 4 times in one day.. but usually it doesn't happen.... wonder why that is..

**Comment by jeske** [comment]
I think I found the problem that is causing the glitching out..

The RunePage stat choices are in the wrong order. Sometimes this is fine, but when the first stat choice is Magic Resist, this is "invalid" in the League client, and uploading makes an invalid rune page with an error.

For example, try to upload this Jhin Page.... You can see that the first two "stat" selections are round circles that represent Magic Resist...

![image](https://user-images.githubusercontent.com/15093/60838070-b835de00-a17e-11e9-99bc-d2c4b20e2a9b.png)

However, you can see from this screenshot of the stat setup, that the round circle "Magic Resist" items have to come in the 2nd and 3rd slot, but not the first.

![image](https://user-images.githubusercontent.com/15093/60838081-c1bf4600-a17e-11e9-9701-a49d5ee5d14e.png)

**Comment by OrangeNote** [comment]
I checked their site and it appears they have switched the ids for "adaptive force" and "magic resist". Can you confirm that's the only case for which it happens or have you found some other pages with different validity issues?

**Comment by jeske** [comment]
Yes, it seems like the problem is on "Korean Builds" AF shows up as MR in RuneBook.  For example, Kayn on Korean Builds.... (but the other sites correctly display adaptive force instead of MR)

![image](https://user-images.githubusercontent.com/15093/60840254-ecf86400-a183-11e9-9846-fbaed7b7812e.png)

That is the only confirmed correlation I can find.... Everytime I have the "upload error" happens, I go into the rune page and the first stat is not selected and RuneBook shows the MR in the first slot (which should have been AF).

> Edit: unfortunately RuneBook doesn't validate pages and the only way to find out if a page is valid is to upload it to the client. The upload process is not an atomic operation so I can't roll it back. That's why it just defaults to a preset page. It's the default client behavior.

Yeah that's not a problem. If there is a way to get the client to select the page even when it has an "error" (aka incomplete fill out), that would be preferrable to what it does now... but if you can't get the league client to do that, I understand.  This problem will go away when you adjust the code for Korean Builds.

**Comment by OrangeNote** [comment]
fixed with the latest release 1597843
