### ISSUE TITLE
U.GG Parsing problem

### ISSUE THREAD

**Issue by 2x9Mon** [OrangeNote/RuneBook#82]
This issue had occurred in the past (#73). But there's a problem with parsing runes from **U.GG** once again, it seems
![image](https://user-images.githubusercontent.com/38780759/60833995-3ec2dd80-a1c8-11e9-94dc-765b75f9e7d7.png)

p.s.
There's also a problem with "Korean Builds". From time to time it gives broken rune pages w/ missing parts, which causes the game to set the default rune page instead

**Comment by OrangeNote** [comment]
u.gg version has been updated, so it should work now.

For Korean builds #81 is probably related
